export const API_REQUEST_LOADING = "API_REQUEST_LOADING";
export const API_REQUEST_SUCCESS = "API_REQUEST_SUCCESS";
export const API_REQUEST_FAILED = "API_REQUEST_FAILED";

export const PRODUCT_DETAIL_LOADING = "PRODUCT_DETAIL_LOADING";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAILED = "PRODUCT_DETAIL_FAILD";

export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
